### ISSUE TITLE
webpackUtils.hasJsxRuntime is not a function

### ISSUE THREAD

**Issue by felschr** [kelvindecosta/gatsby-plugin-eslint-config#4]
Using this library causes the following error when running `eslint`:
```console
$ eslint --fix "src/**/*.{js,ts}{,x}"

 ERROR


Oops! Something went wrong! :(

ESLint: 8.11.0

TypeError: Failed to load plugin 'gatsby' declared in '.eslintrc.js': webpackUtils.hasJsxRuntime is not a function
Referenced from: /home/felschr/dev/my-project/clients/preregistration/.eslintrc.js
    at Object.<anonymous> (/home/felschr/dev/my-project/node_modules/eslint-plugin-gatsby/index.js:19:20)
    at Module._compile (/home/felschr/dev/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ConfigArrayFactory._loadPlugin (/home/felschr/dev/my-project/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1070:42)
    at ConfigArrayFactory._loadExtendedPluginConfig (/home/felschr/dev/my-project/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:871:29)
    at ConfigArrayFactory._loadExtends (/home/felschr/dev/my-project/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:792:29)
```

I'm on `gatsby@4.2.0`.

**Comment by timbakkum** [comment]
running into same issue :/  came here from your suggestion here: https://github.com/gatsbyjs/gatsby/discussions/23666#discussioncomment-880468 
I'm on gatsby 4.13.1

**Comment by Mike-Logit** [comment]
Same but I'm on gatsby ^3.14.6

**Comment by holly-cummins** [comment]
I had some success using the non-plugin solution in https://github.com/gatsbyjs/gatsby/discussions/23666#discussioncomment-880468,

but in `gatsby-eslint.js`, replacing the import of `reactHasJsxRuntime` with this:

```
   const reactHasJsxRuntime = () => false
```
